<a href="https://colab.research.google.com/github/Aeagon07/Natural-Language-Processing-/blob/main/Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bag Of Word**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'text': ['people watch campusx', 'campusx wath campusx', 'people write comment', 'campusx write comment'], 'output': [1, 1, 0, 0]})
df

text  output
0   people watch campusx       1
1   campusx wath campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
# Vocab
print(cv.vocabulary_)
# the word is alphabetically arranged so they give them number so when your array gives you [1, 0, 0, 0, 0] that means there is only campusx which is present

{'people': 2, 'watch': 3, 'campusx': 0, 'wath': 4, 'write': 5, 'comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 1 1 0 0]]
[[2 0 0 0 1 0]]
[[0 1 1 0 0 1]]


In [ ]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 0, 1]])

# **N-Grams**

In [ ]:
#  This is same as the bag of words cause BoW is also a Uni-Gram special technique of N-Grams
df

text  output
0   people watch campusx       1
1   campusx wath campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
cv2 = CountVectorizer(ngram_range=(2, 2)) # for Bi-Grams {default ngram_range is set to (1, 1)}

In [ ]:
bow = cv2.fit_transform(df['text'])

In [ ]:
print(cv2.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx wath': 0, 'wath campusx': 5, 'people write': 3, 'write comment': 6, 'campusx write': 1}


In [ ]:
print(bow[0].toarray()) # D1

[[0 0 1 0 1 0 0]]


# **Tf-Idf**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.44809973, 0.        , 0.55349232, 0.70203482, 0.        ,
        0.        ],
       [0.78722298, 0.        , 0.        , 0.        , 0.61666846,
        0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.        ,
        0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.        ,
        0.61366674]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

# Why these values are higher => they have very different technique that after log they added (+1) so they avoid those terms which are occurs in all the corpus
# and so it's log value become 0 and after multiplication with the tf it will give you 0 so that...

[1.22314355 1.51082562 1.51082562 1.91629073 1.91629073 1.51082562]
['campusx' 'comment' 'people' 'watch' 'wath' 'write']


In [ ]:
# Interview Question => Why you taking log during idf calculation
# => so if idf terms are getting the higher values like 10 thousand or 1 lakh then after tf multiplication the idf one is more dominaing factor. but we want
# both enities contributing same so to avoid and smothing out such situation you uses the log